/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.proyecto.parqueaderospop.vistas;

import co.unicauca.proyecto.parqueaderospop.controlador.CtrlRegVehiculo;
import co.unicauca.proyecto.parqueaderospop.modelo.ConsultasFicha;
import co.unicauca.proyecto.parqueaderospop.modelo.ConsultasRegVehiculo;
import co.unicauca.proyecto.parqueaderospop.modelo.ConsultasVehiculo;
import co.unicauca.proyecto.parqueaderospop.modelo.Ficha;
import co.unicauca.proyecto.parqueaderospop.modelo.RegistroVehiculo;
import co.unicauca.proyecto.parqueaderospop.modelo.Vehiculo;

/**
 *
 * @author danny
 */
public class GUIPaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPaginaPrincipal
     */
    public GUIPaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegVehiParque = new javax.swing.JButton();
        btnRegParqueadero = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRegVehiculo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        btnRegVehiParque.setText("Registrar Vehiculo en el parqueadero");

        btnRegParqueadero.setText("Registar Parqueadero");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parqueaderos Popayán");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        btnRegVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnRegVehiculo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnRegVehiculo.setText("Registrar Vehiculo");
        btnRegVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVehiculoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnRegVehiculo)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnRegVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    //invoca a la vista GUIRegistrarPrincipal y ademas hace un llamado el controlador CtrlRegVehiculo
    private void btnRegVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVehiculoActionPerformed
       
        java.awt.EventQueue.invokeLater(new Runnable(){
           public void run(){
               GUIRegistrarVehiculo reg = new GUIRegistrarVehiculo();
               
               reg.setLocation(700,200);
               
               
               Vehiculo vehi = new Vehiculo();
               ConsultasVehiculo conVehi = new ConsultasVehiculo();    
               RegistroVehiculo clsregVehiculo = new RegistroVehiculo();
               ConsultasRegVehiculo conRegVehi = new ConsultasRegVehiculo();
               Ficha fi = new Ficha();
               ConsultasFicha conFi = new ConsultasFicha();
               CtrlRegVehiculo ctrlRegVehiculo = new CtrlRegVehiculo(clsregVehiculo,conRegVehi,vehi,conVehi,fi,conFi,reg);
               ctrlRegVehiculo.iniciar();
               reg.setVisible(true);
               //new GUIPaginaPrincipal().setVisible(false);
           } 
        });
    }//GEN-LAST:event_btnRegVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegParqueadero;
    public javax.swing.JButton btnRegVehiParque;
    private javax.swing.JButton btnRegVehiculo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
