/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.proyecto.parqueaderospop.vistas;

import co.unicauca.proyecto.parqueaderospop.vistas.GUIPaginaPrincipal;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author danny
 */
public class GUIRegistrarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form GUIIngresarVehiculo
     */
    
    public GUIRegistrarVehiculo() {
        initComponents();
        jcmbNumCascos.setEnabled(false);//desactiva el numero de numero de cascos
        jtxtFCasillero.setEnabled(false);//desactiva la caja casillero
        btnGuardar.setEnabled(false);//desactiva el boton guardar
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbPlaca = new javax.swing.JLabel();
        jtxtFPlaca = new javax.swing.JTextField();
        jlbNumFicha = new javax.swing.JLabel();
        jtxtFNumFicha = new javax.swing.JTextField();
        jlbTipoVehiculo = new javax.swing.JLabel();
        jcmbTipoVehiculo = new javax.swing.JComboBox<>();
        jlbHoraFechaIng = new javax.swing.JLabel();
        jchbLlaves = new javax.swing.JCheckBox();
        jlbNumCascos = new javax.swing.JLabel();
        jcmbNumCascos = new javax.swing.JComboBox<>();
        btnVincular = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtFCasillero = new javax.swing.JTextField();
        jtxtFHoraFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Vehiculo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlbPlaca.setText("Placa");

        jlbNumFicha.setText("Numero de ficha");

        jtxtFNumFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFNumFichaKeyTyped(evt);
            }
        });

        jlbTipoVehiculo.setText("Tipo Vehiculo");

        jcmbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));
        jcmbTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTipoVehiculoActionPerformed(evt);
            }
        });

        jlbHoraFechaIng.setText("Hora y fecha entrada");

        jchbLlaves.setText("Deja llaves");

        jlbNumCascos.setText("Numero de cascos");

        jcmbNumCascos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        btnVincular.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnVincular.setText("Vincular");
        btnVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Casillero");

        jtxtFCasillero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFCasilleroKeyTyped(evt);
            }
        });

        jtxtFHoraFecha.setText("-");
        jtxtFHoraFecha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtxtFHoraFechaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jlbPlaca)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbHoraFechaIng)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlbTipoVehiculo)
                                        .addComponent(jlbNumFicha)))
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtFPlaca)
                            .addComponent(jtxtFNumFicha)
                            .addComponent(jcmbTipoVehiculo, 0, 161, Short.MAX_VALUE)
                            .addComponent(jtxtFHoraFecha)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jchbLlaves)
                                .addGap(18, 18, 18)
                                .addComponent(jlbNumCascos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVincular)
                                .addGap(39, 39, 39)
                                .addComponent(btnGuardar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45)
                                .addComponent(jtxtFCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbNumCascos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 330, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumFicha)
                    .addComponent(jtxtFNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPlaca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoVehiculo)
                    .addComponent(jcmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHoraFechaIng)
                    .addComponent(jtxtFHoraFecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchbLlaves)
                    .addComponent(jlbNumCascos)
                    .addComponent(jcmbNumCascos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVincular))
                .addGap(32, 32, 32)
                .addComponent(btnRegresar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularActionPerformed
        // TODO add your handling code here:
//        if (jtxtFNumFicha.getText().isEmpty() || jtxtFPlaca.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "El campo Numero de ficha o el campo placa no pueden estar vacios");
//        }else{
//            JOptionPane.showMessageDialog(null, "Ficha Vinculada de forma correcta");
//        }
    }//GEN-LAST:event_btnVincularActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed
    //Metodo que desactiva los campos numero de cascos y numero de casillero si es un carro y los activa si es una moto 
    private void jcmbTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTipoVehiculoActionPerformed
        // TODO add your handling code here:
        if (jcmbTipoVehiculo.getSelectedItem().toString().equals("Carro")){
            jcmbNumCascos.setEnabled(false);
            jtxtFCasillero.setEnabled(false);
        }else{
            jcmbNumCascos.setEnabled(true);
            jtxtFCasillero.setEnabled(true);
        }
    }//GEN-LAST:event_jcmbTipoVehiculoActionPerformed

   //evita que se ingresen caracteres diferentes a los numeros en el numero de ficha
    private void jtxtFNumFichaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFNumFichaKeyTyped
       
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9') evt.consume();
    }//GEN-LAST:event_jtxtFNumFichaKeyTyped
    //evita que se ingresen caracteres diferentes a los numeros en el numero de casillero
    private void jtxtFCasilleroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFCasilleroKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9') evt.consume();
    }//GEN-LAST:event_jtxtFCasilleroKeyTyped
    
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable(){
           public void run(){
               //GUIRegistrarVehiculo frm = new GUIRegistrarVehiculo();
               dispose();
           } 
        });
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jtxtFHoraFechaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtxtFHoraFechaAncestorAdded
        Date date =  new Date();
       DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");  
       DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
       jtxtFHoraFecha.setText(hourFormat.format(date)+"  "+dateFormat.format(date));
    }//GEN-LAST:event_jtxtFHoraFechaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarVehiculo().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnVincular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JCheckBox jchbLlaves;
    public javax.swing.JComboBox<String> jcmbNumCascos;
    public javax.swing.JComboBox<String> jcmbTipoVehiculo;
    private javax.swing.JLabel jlbHoraFechaIng;
    private javax.swing.JLabel jlbNumCascos;
    private javax.swing.JLabel jlbNumFicha;
    private javax.swing.JLabel jlbPlaca;
    private javax.swing.JLabel jlbTipoVehiculo;
    public javax.swing.JTextField jtxtFCasillero;
    public javax.swing.JLabel jtxtFHoraFecha;
    public javax.swing.JTextField jtxtFNumFicha;
    public javax.swing.JTextField jtxtFPlaca;
    // End of variables declaration//GEN-END:variables
}
